#include "xwayland/xwm.h"

#include <cstdlib>
#include <cstring>
#include <unordered_map>
#include <vector>

#include <xcb/composite.h>
#include <xcb/xcb.h>
#include <xcb/xcbext.h>  // xcb_poll_for_reply
#include <xcb/xfixes.h>

#include "log/log.h"

namespace overdraw::xwayland {

namespace {

// Indexed by AtomIndex. Keep in lockstep with the enum in xwm.h.
const char* const ATOM_NAMES[ATOM_COUNT] = {
    "WL_SURFACE_SERIAL",
    "WM_PROTOCOLS",
    "WM_DELETE_WINDOW",
    "WM_TAKE_FOCUS",
    "WM_STATE",
    "WM_NAME",
    "WM_CLASS",
    "WM_NORMAL_HINTS",
    "WM_HINTS",
    "WM_TRANSIENT_FOR",
    "_NET_WM_NAME",
    "_NET_WM_STATE",
    "_NET_WM_WINDOW_TYPE",
    "_NET_WM_PID",
    "_NET_WM_STATE_FULLSCREEN",
    "_NET_WM_STATE_MAXIMIZED_VERT",
    "_NET_WM_STATE_MAXIMIZED_HORZ",
    "_NET_WM_STATE_MODAL",
    "_NET_WM_STATE_FOCUSED",
    "_NET_ACTIVE_WINDOW",
    "_NET_WM_WINDOW_TYPE_NORMAL",
    "_NET_WM_WINDOW_TYPE_DIALOG",
    "_NET_WM_WINDOW_TYPE_UTILITY",
    "_NET_WM_WINDOW_TYPE_MENU",
    "_NET_WM_WINDOW_TYPE_DROPDOWN_MENU",
    "_NET_WM_WINDOW_TYPE_POPUP_MENU",
    "_NET_WM_WINDOW_TYPE_TOOLTIP",
    "_NET_WM_WINDOW_TYPE_COMBO",
    "_NET_WM_WINDOW_TYPE_SPLASH",
    "_NET_SUPPORTED",
    "_NET_SUPPORTING_WM_CHECK",
    "_NET_STARTUP_ID",
    "_NET_WM_ICON",
    "UTF8_STRING",
    "CLIPBOARD",
    "PRIMARY",
    "TARGETS",
    "TIMESTAMP",
    "INCR",
    "TEXT",
    "STRING",
    "MULTIPLE",
    "DELETE",
    "CLIPBOARD_MANAGER",
    "_OVERDRAW_SELECTION",
};

// One outstanding xcb_get_property reply. Keyed by `cookieId` on the TS side;
// the xcb sequence number is what xcb_poll_for_reply matches against.
struct PendingProperty {
    uint32_t cookieId = 0;
    uint32_t window = 0;
    uint32_t atom = 0;
    unsigned int sequence = 0;  // xcb cookie's .sequence
};

// One outstanding xcb_get_atom_name reply.
struct PendingAtomName {
    uint32_t cookieId = 0;
    uint32_t atom = 0;
    unsigned int sequence = 0;
};

}  // namespace

const char* atomName(int i) {
    return (i >= 0 && i < ATOM_COUNT) ? ATOM_NAMES[i] : "";
}

// Tracked X-side geometry of a window. Updated on CreateNotify and
// ConfigureNotify; read on MapNotify so the TS side knows the rect Xwayland
// has on the window at map time (which may differ from CreateNotify's
// initial rect, e.g. for override-redirect windows that issue
// ConfigureWindow between create and map to position their menu).
struct TrackedRect {
    int32_t x = 0, y = 0, width = 0, height = 0;
};

struct XwmConn {
    xcb_connection_t* conn = nullptr;
    xcb_screen_t* screen = nullptr;
    xcb_window_t root = 0;
    xcb_atom_t atoms[ATOM_COUNT] = {0};

    // Pending GetProperty replies. Walked every xwmProcess call.
    std::vector<PendingProperty> pending;
    // Pending GetAtomName replies.
    std::vector<PendingAtomName> pendingAtomName;
    uint32_t nextCookieId = 1;

    // xfixes extension: the first-event opcode for selection-notify
    // (selection-bridge events arrive as (response_type & 0x7f) ==
    // xfixesFirstEvent + XCB_XFIXES_SELECTION_NOTIFY).
    uint8_t xfixesFirstEvent = 0;
    bool xfixesAvailable = false;

    // Per-window geometry tracker. Populated on CreateNotify, updated on
    // ConfigureNotify, cleared on DestroyNotify.
    std::unordered_map<uint32_t, TrackedRect> rects;

    // The bookkeeper window: 1x1 override-redirect, mapped offscreen. The
    // XWM SetInputFocuses this when no managed X client should hold X-side
    // focus (e.g. focus moved to a Wayland client or to a NULL focus
    // target). Created in xwmConnect; destroyed in xwmDisconnect.
    xcb_window_t bookkeeper = 0;

    // Default cursor set on the root window so X11 clients that don't
    // define their own inherit it. Created in xwmConnect, freed in
    // xwmDisconnect.
    xcb_cursor_t rootCursor = 0;

    // Sequence of the most recent SetInputFocus request the XWM issued. X
    // FocusIn events with .sequence older than this are stale -- they were
    // generated by a focus change WE initiated, OR by a client that lost
    // the race to our subsequent SetInputFocus. The TS side compares each
    // FocusIn event's sequence to this and discards stale ones.
    uint32_t lastFocusSeq = 0;
};

XwmConn* xwmConnect(int wmFd) {
    auto* x = new XwmConn();
    x->conn = xcb_connect_to_fd(wmFd, nullptr);
    if (xcb_connection_has_error(x->conn)) {
        LOG_ERR(Wayland, "[xwm] xcb_connect_to_fd failed");
        xcb_disconnect(x->conn);  // also closes wmFd
        delete x;
        return nullptr;
    }
    x->screen = xcb_setup_roots_iterator(xcb_get_setup(x->conn)).data;
    if (!x->screen) {
        LOG_ERR(Wayland, "[xwm] no screen");
        xcb_disconnect(x->conn);
        delete x;
        return nullptr;
    }
    x->root = x->screen->root;

    // Become the WM: redirect substructure (intercept map/configure requests)
    // and watch child lifecycle + root property changes.
    const uint32_t rootMask = XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT |
                              XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY |
                              XCB_EVENT_MASK_PROPERTY_CHANGE;
    xcb_change_window_attributes(x->conn, x->root, XCB_CW_EVENT_MASK, &rootMask);

    // Composite-redirect the root's subwindows (manual) so Xwayland presents
    // each toplevel as its own wl_surface instead of painting the root.
    xcb_composite_redirect_subwindows(x->conn, x->root, XCB_COMPOSITE_REDIRECT_MANUAL);

    // Root cursor: an X11 window that never calls XDefineCursor inherits its
    // cursor from an ancestor, ultimately the root. With no root cursor such
    // a window resolves to None, which Xwayland reports to the compositor as
    // wl_pointer.set_cursor(NULL) -- i.e. "hide the cursor". Set a standard
    // left-pointer glyph on the root so those windows show a cursor; a window
    // that explicitly hides its cursor still sends NULL and still hides.
    xcb_font_t cursorFont = xcb_generate_id(x->conn);
    xcb_open_font(x->conn, cursorFont, 6, "cursor");
    x->rootCursor = xcb_generate_id(x->conn);
    // XC_left_ptr = 68 in the X cursor font; its shape mask is the next glyph.
    xcb_create_glyph_cursor(x->conn, x->rootCursor, cursorFont, cursorFont,
                            68, 69, 0, 0, 0, 0xffff, 0xffff, 0xffff);
    xcb_change_window_attributes(x->conn, x->root, XCB_CW_CURSOR, &x->rootCursor);
    xcb_close_font(x->conn, cursorFont);

    // xfixes: required for selection-owner-change notifications. Query the
    // extension first-event opcode and bump the negotiated version (any
    // version that supports xfixes-selection is fine; we only need v1).
    const xcb_query_extension_reply_t* xfixesExt =
        xcb_get_extension_data(x->conn, &xcb_xfixes_id);
    if (xfixesExt && xfixesExt->present) {
        xcb_xfixes_query_version_cookie_t qvc = xcb_xfixes_query_version(
            x->conn, XCB_XFIXES_MAJOR_VERSION, XCB_XFIXES_MINOR_VERSION);
        xcb_xfixes_query_version_reply_t* qv =
            xcb_xfixes_query_version_reply(x->conn, qvc, nullptr);
        if (qv) {
            x->xfixesFirstEvent = xfixesExt->first_event;
            x->xfixesAvailable = true;
            free(qv);
        }
    }
    if (!x->xfixesAvailable) {
        LOG_WARN(Wayland,
            "[xwm] xfixes unavailable; clipboard / primary-selection bridge "
            "will not function");
    }

    // Intern atoms (pipelined: issue all, then collect).
    xcb_intern_atom_cookie_t cookies[ATOM_COUNT];
    for (int i = 0; i < ATOM_COUNT; ++i) {
        cookies[i] = xcb_intern_atom(
            x->conn, 0, static_cast<uint16_t>(std::strlen(ATOM_NAMES[i])), ATOM_NAMES[i]);
    }
    for (int i = 0; i < ATOM_COUNT; ++i) {
        xcb_intern_atom_reply_t* r = xcb_intern_atom_reply(x->conn, cookies[i], nullptr);
        if (r) {
            x->atoms[i] = r->atom;
            free(r);
        }
    }

    // Bookkeeper window: 1x1 override-redirect, parked offscreen. Selects
    // FOCUS_CHANGE so we can observe what X is doing with focus when the
    // bookkeeper holds it (mostly a noise filter; it doesn't drive any
    // policy). Mapped so SetInputFocus on it actually grants focus (X
    // refuses to focus an unmapped window).
    x->bookkeeper = xcb_generate_id(x->conn);
    const uint32_t bkValues[2] = { 1 /*override_redirect*/,
                                   XCB_EVENT_MASK_FOCUS_CHANGE };
    xcb_create_window(x->conn,
        XCB_COPY_FROM_PARENT, x->bookkeeper, x->root,
        -100, -100, 1, 1, 0,
        XCB_WINDOW_CLASS_COPY_FROM_PARENT,
        XCB_COPY_FROM_PARENT,
        XCB_CW_OVERRIDE_REDIRECT | XCB_CW_EVENT_MASK,
        bkValues);
    xcb_map_window(x->conn, x->bookkeeper);

    xcb_flush(x->conn);
    return x;
}

void xwmDisconnect(XwmConn* x) {
    if (!x) return;
    if (x->conn && x->bookkeeper) {
        xcb_destroy_window(x->conn, x->bookkeeper);
    }
    if (x->conn && x->rootCursor) {
        xcb_free_cursor(x->conn, x->rootCursor);
    }
    if (x->conn) xcb_disconnect(x->conn);
    delete x;
}

int xwmFd(XwmConn* x) { return xcb_get_file_descriptor(x->conn); }

uint32_t xwmAtom(XwmConn* x, int idx) {
    if (idx < 0 || idx >= ATOM_COUNT) return 0;
    return x->atoms[idx];
}

namespace {

// Drain any pending GetProperty replies that xcb has already buffered. We poll
// each outstanding cookie; xcb_poll_for_reply does not block. A returned
// reply (or error) consumes that pending entry.
void drainPropertyReplies(XwmConn* x,
                          const std::function<void(const XwmEvent&)>& cb) {
    auto it = x->pending.begin();
    while (it != x->pending.end()) {
        void* reply = nullptr;
        xcb_generic_error_t* err = nullptr;
        const int ready = xcb_poll_for_reply(x->conn, it->sequence, &reply, &err);
        if (ready == 0) { ++it; continue; }  // not yet -- keep pending

        XwmEvent o;
        o.type = XwmEvent::PropertyReply;
        o.window = it->window;
        o.atom = it->atom;
        o.cookieId = it->cookieId;
        if (reply != nullptr) {
            auto* r = static_cast<xcb_get_property_reply_t*>(reply);
            o.replyType = r->type;
            o.format = r->format;
            o.length = static_cast<uint32_t>(xcb_get_property_value_length(r));
            o.data = static_cast<const uint8_t*>(xcb_get_property_value(r));
            cb(o);
            free(reply);
        } else {
            // Error or BadWindow: deliver an empty reply (format=0) so the
            // TS state machine can clear the pending entry.
            cb(o);
            if (err) free(err);
        }
        it = x->pending.erase(it);
    }
}

// Drain pending GetAtomName replies. Mirrors drainPropertyReplies; the
// reply carries a UTF-8 name borrowed from xcb's reply buffer.
void drainAtomNameReplies(XwmConn* x,
                          const std::function<void(const XwmEvent&)>& cb) {
    auto it = x->pendingAtomName.begin();
    while (it != x->pendingAtomName.end()) {
        void* reply = nullptr;
        xcb_generic_error_t* err = nullptr;
        const int ready = xcb_poll_for_reply(x->conn, it->sequence, &reply, &err);
        if (ready == 0) { ++it; continue; }

        XwmEvent o;
        o.type = XwmEvent::AtomNameReply;
        o.atom = it->atom;
        o.cookieId = it->cookieId;
        if (reply != nullptr) {
            auto* r = static_cast<xcb_get_atom_name_reply_t*>(reply);
            o.data = reinterpret_cast<const uint8_t*>(xcb_get_atom_name_name(r));
            o.length = static_cast<uint32_t>(xcb_get_atom_name_name_length(r));
            cb(o);
            free(reply);
        } else {
            // Error: deliver an empty name so the TS state machine clears
            // the pending entry.
            cb(o);
            if (err) free(err);
        }
        it = x->pendingAtomName.erase(it);
    }
}

}  // namespace

bool xwmProcess(XwmConn* x, const std::function<void(const XwmEvent&)>& cb) {
    xcb_generic_event_t* ev;
    while ((ev = xcb_poll_for_event(x->conn))) {
        switch (ev->response_type & 0x7f) {
            case XCB_CREATE_NOTIFY: {
                auto* e = reinterpret_cast<xcb_create_notify_event_t*>(ev);
                // Don't surface internal WM-owned windows (the bookkeeper) to
                // the TS layer. It's our private focus-recipient; the TS XWM
                // would otherwise see it as an OR overlay and try to manage it.
                if (e->window == x->bookkeeper) break;
                // Select per-window events (focus + property changes); this also
                // routes the window's client-messages (incl. WL_SURFACE_SERIAL)
                // to us.
                const uint32_t mask =
                    XCB_EVENT_MASK_FOCUS_CHANGE | XCB_EVENT_MASK_PROPERTY_CHANGE;
                xcb_change_window_attributes(x->conn, e->window, XCB_CW_EVENT_MASK, &mask);
                // Track the initial geometry so MapNotify can report the
                // current rect even if no ConfigureNotify has fired yet.
                x->rects[e->window] = { e->x, e->y, e->width, e->height };
                XwmEvent o;
                o.type = XwmEvent::Create;
                o.window = e->window;
                o.x = e->x;
                o.y = e->y;
                o.width = e->width;
                o.height = e->height;
                o.overrideRedirect = e->override_redirect;
                cb(o);
                break;
            }
            case XCB_DESTROY_NOTIFY: {
                auto* e = reinterpret_cast<xcb_destroy_notify_event_t*>(ev);
                if (e->window == x->bookkeeper) break;
                x->rects.erase(e->window);
                XwmEvent o;
                o.type = XwmEvent::Destroy;
                o.window = e->window;
                cb(o);
                break;
            }
            case XCB_MAP_REQUEST: {
                auto* e = reinterpret_cast<xcb_map_request_event_t*>(ev);
                XwmEvent o;
                o.type = XwmEvent::MapRequest;
                o.window = e->window;
                cb(o);
                break;
            }
            case XCB_MAP_NOTIFY: {
                auto* e = reinterpret_cast<xcb_map_notify_event_t*>(ev);
                if (e->window == x->bookkeeper) break;
                XwmEvent o;
                o.type = XwmEvent::MapNotify;
                o.window = e->window;
                o.overrideRedirect = e->override_redirect;
                // Carry the current tracked rect so the TS side has the X-side
                // geometry at map time (CreateNotify's rect can be stale if
                // the client called ConfigureWindow between create and map).
                auto it = x->rects.find(e->window);
                if (it != x->rects.end()) {
                    o.x = it->second.x;
                    o.y = it->second.y;
                    o.width = it->second.width;
                    o.height = it->second.height;
                }
                cb(o);
                break;
            }
            case XCB_UNMAP_NOTIFY: {
                auto* e = reinterpret_cast<xcb_unmap_notify_event_t*>(ev);
                if (e->window == x->bookkeeper) break;
                XwmEvent o;
                o.type = XwmEvent::UnmapNotify;
                o.window = e->window;
                cb(o);
                break;
            }
            case XCB_CONFIGURE_REQUEST: {
                auto* e = reinterpret_cast<xcb_configure_request_event_t*>(ev);
                XwmEvent o;
                o.type = XwmEvent::ConfigureRequest;
                o.window = e->window;
                o.x = e->x;
                o.y = e->y;
                o.width = e->width;
                o.height = e->height;
                cb(o);
                break;
            }
            case XCB_CONFIGURE_NOTIFY: {
                auto* e = reinterpret_cast<xcb_configure_notify_event_t*>(ev);
                if (e->window == x->bookkeeper) break;
                // Track for future MapNotify reads. Skip our own synthetic
                // ConfigureNotifies (top bit of response_type set by
                // xcb_send_event) so we don't ping-pong on our own state.
                if ((ev->response_type & 0x80) == 0) {
                    x->rects[e->window] = { e->x, e->y, e->width, e->height };
                }
                XwmEvent o;
                o.type = XwmEvent::ConfigureNotify;
                o.window = e->window;
                o.x = e->x;
                o.y = e->y;
                o.width = e->width;
                o.height = e->height;
                cb(o);
                break;
            }
            case XCB_FOCUS_IN: {
                auto* e = reinterpret_cast<xcb_focus_in_event_t*>(ev);
                // Drop pointer-detail (cursor-motion focus chatter) and the
                // grab/ungrab modes (those are an X client temporarily
                // grabbing input, not a focus-policy event).
                if (e->detail == XCB_NOTIFY_DETAIL_POINTER) break;
                if (e->mode == XCB_NOTIFY_MODE_GRAB
                    || e->mode == XCB_NOTIFY_MODE_UNGRAB) break;
                // The bookkeeper's FocusIns are noise -- they fire when we
                // park X focus there; the TS side doesn't care.
                if (e->event == x->bookkeeper) break;
                XwmEvent o;
                o.type = XwmEvent::FocusIn;
                o.window = e->event;
                // X event sequence is 16-bit on the wire; widen to 32. TS
                // compares against the 32-bit sequence stashed in
                // lastFocusSeq, handling u16 wraparound with the same
                // half-window-rev-distance trick.
                o.eventSequence = e->sequence;
                cb(o);
                break;
            }
            case XCB_PROPERTY_NOTIFY: {
                auto* e = reinterpret_cast<xcb_property_notify_event_t*>(ev);
                XwmEvent o;
                o.type = XwmEvent::PropertyNotify;
                o.window = e->window;
                o.atom = e->atom;
                // XCB_PROPERTY_NEW_VALUE = 0, XCB_PROPERTY_DELETE = 1.
                // INCR pumps key off the distinction (incoming on NEW_VALUE,
                // outgoing on DELETE).
                o.propertyState = e->state;
                cb(o);
                break;
            }
            case XCB_SELECTION_REQUEST: {
                auto* e = reinterpret_cast<xcb_selection_request_event_t*>(ev);
                XwmEvent o;
                o.type = XwmEvent::SelectionRequest;
                o.requestor = e->requestor;
                o.selection = e->selection;
                o.target = e->target;
                o.property = e->property;  // 0 = obsolete-client convention
                o.timestamp = e->time;
                cb(o);
                break;
            }
            case XCB_SELECTION_NOTIFY: {
                auto* e = reinterpret_cast<xcb_selection_notify_event_t*>(ev);
                XwmEvent o;
                o.type = XwmEvent::SelectionNotify;
                o.requestor = e->requestor;
                o.selection = e->selection;
                o.target = e->target;
                o.property = e->property;  // 0 = conversion refused
                o.timestamp = e->time;
                cb(o);
                break;
            }
            case XCB_CLIENT_MESSAGE: {
                auto* e = reinterpret_cast<xcb_client_message_event_t*>(ev);
                if (e->type == x->atoms[ATOM_WL_SURFACE_SERIAL] && e->format == 32) {
                    const uint32_t lo = e->data.data32[0];
                    const uint32_t hi = e->data.data32[1];
                    XwmEvent o;
                    o.type = XwmEvent::SurfaceSerial;
                    o.window = e->window;
                    o.serial = (static_cast<uint64_t>(hi) << 32) | lo;
                    cb(o);
                } else if (e->type == x->atoms[ATOM_NET_WM_STATE] && e->format == 32) {
                    // EWMH §5.7: post-map state changes arrive as a root-window
                    // ClientMessage (action + up to two state atoms), not as a
                    // property write by the client.
                    XwmEvent o;
                    o.type = XwmEvent::NetWmState;
                    o.window = e->window;
                    o.stateAction = e->data.data32[0];
                    o.stateAtom1 = e->data.data32[1];
                    o.stateAtom2 = e->data.data32[2];
                    cb(o);
                }
                break;
            }
            default:
                if (x->xfixesAvailable
                    && (ev->response_type & 0x7f)
                        == x->xfixesFirstEvent + XCB_XFIXES_SELECTION_NOTIFY) {
                    auto* e = reinterpret_cast<
                        xcb_xfixes_selection_notify_event_t*>(ev);
                    XwmEvent o;
                    o.type = XwmEvent::XfixesSelectionNotify;
                    o.selection = e->selection;
                    o.selectionOwner = e->owner;  // XCB_NONE = no owner
                    o.timestamp = e->timestamp;
                    cb(o);
                }
                break;
        }
        free(ev);
    }

    drainPropertyReplies(x, cb);
    drainAtomNameReplies(x, cb);

    return !xcb_connection_has_error(x->conn);
}

void xwmMapWindow(XwmConn* x, uint32_t window) {
    xcb_map_window(x->conn, window);
    xcb_flush(x->conn);
}

void xwmConfigureWindow(XwmConn* x, uint32_t window,
                        int32_t xx, int32_t yy, int32_t w, int32_t h) {
    const uint32_t values[] = {
        static_cast<uint32_t>(xx), static_cast<uint32_t>(yy),
        static_cast<uint32_t>(w), static_cast<uint32_t>(h),
    };
    const uint16_t mask = XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y |
                          XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT;
    xcb_configure_window(x->conn, window, mask, values);
    xcb_flush(x->conn);
}

void xwmSendConfigureNotify(XwmConn* x, uint32_t window,
                            int32_t xx, int32_t yy, int32_t w, int32_t h) {
    xcb_configure_notify_event_t ev = {};
    ev.response_type = XCB_CONFIGURE_NOTIFY;
    ev.event = window;
    ev.window = window;
    ev.above_sibling = XCB_NONE;
    ev.x = static_cast<int16_t>(xx);
    ev.y = static_cast<int16_t>(yy);
    ev.width = static_cast<uint16_t>(w);
    ev.height = static_cast<uint16_t>(h);
    ev.border_width = 0;
    ev.override_redirect = 0;
    xcb_send_event(x->conn, /*propagate=*/0, window,
                   XCB_EVENT_MASK_STRUCTURE_NOTIFY,
                   reinterpret_cast<const char*>(&ev));
    xcb_flush(x->conn);
}

uint32_t xwmGetProperty(XwmConn* x, uint32_t window, uint32_t atom,
                        uint32_t maxLengthWords) {
    // delete=0, type=AnyPropertyType(0), offset=0, long_length=maxLengthWords.
    xcb_get_property_cookie_t c = xcb_get_property(
        x->conn, /*_delete=*/0, window, atom, /*type=*/0,
        /*long_offset=*/0, maxLengthWords);
    xcb_flush(x->conn);
    PendingProperty p;
    p.cookieId = x->nextCookieId++;
    if (p.cookieId == 0) p.cookieId = x->nextCookieId++;  // skip 0 sentinel
    p.window = window;
    p.atom = atom;
    p.sequence = c.sequence;
    x->pending.push_back(p);
    return p.cookieId;
}

void xwmSendWmProtocol(XwmConn* x, uint32_t window, uint32_t proto,
                       uint32_t timestamp) {
    xcb_client_message_event_t ev = {};
    ev.response_type = XCB_CLIENT_MESSAGE;
    ev.format = 32;
    ev.window = window;
    ev.type = x->atoms[ATOM_WM_PROTOCOLS];
    ev.data.data32[0] = proto;
    ev.data.data32[1] = timestamp;
    ev.data.data32[2] = 0;
    ev.data.data32[3] = 0;
    ev.data.data32[4] = 0;
    xcb_send_event(x->conn, /*propagate=*/0, window, XCB_EVENT_MASK_NO_EVENT,
                   reinterpret_cast<const char*>(&ev));
    xcb_flush(x->conn);
}

void xwmKillClient(XwmConn* x, uint32_t window) {
    xcb_kill_client(x->conn, window);
    xcb_flush(x->conn);
}

uint32_t xwmSetInputFocus(XwmConn* x, uint32_t window, uint32_t timestamp) {
    // RevertToPointerRoot: if `window` later becomes unviewable, focus
    // reverts to whoever owns the pointer. Standard ICCCM choice.
    xcb_void_cookie_t c = xcb_set_input_focus_checked(
        x->conn, XCB_INPUT_FOCUS_POINTER_ROOT, window, timestamp);
    x->lastFocusSeq = c.sequence;
    xcb_flush(x->conn);
    return c.sequence;
}

void xwmChangeProperty(XwmConn* x, uint32_t window, uint32_t atom,
                       uint32_t type, uint8_t format,
                       const void* data, uint32_t nelements) {
    xcb_change_property(x->conn, XCB_PROP_MODE_REPLACE, window, atom, type,
                        format, nelements, data);
    xcb_flush(x->conn);
}

void xwmDeleteProperty(XwmConn* x, uint32_t window, uint32_t atom) {
    xcb_delete_property(x->conn, window, atom);
    xcb_flush(x->conn);
}

uint32_t xwmBookkeeperWindow(XwmConn* x) { return x->bookkeeper; }
uint32_t xwmRootWindow(XwmConn* x) { return x->root; }

uint32_t xwmCreateSelectionWindow(XwmConn* x, uint32_t eventMask, bool inputOnly) {
    if (!x->conn) return 0;
    const xcb_window_t w = xcb_generate_id(x->conn);
    if (w == 0) return 0;
    const uint32_t values[1] = { eventMask };
    xcb_create_window(x->conn,
        XCB_COPY_FROM_PARENT, w, x->root,
        0, 0, 1, 1, 0,
        inputOnly ? XCB_WINDOW_CLASS_INPUT_ONLY : XCB_WINDOW_CLASS_INPUT_OUTPUT,
        XCB_COPY_FROM_PARENT,
        XCB_CW_EVENT_MASK, values);
    xcb_flush(x->conn);
    return w;
}

void xwmDestroyWindow(XwmConn* x, uint32_t window) {
    if (!x->conn || window == 0) return;
    xcb_destroy_window(x->conn, window);
    xcb_flush(x->conn);
}

void xwmSetSelectionOwner(XwmConn* x, uint32_t selectionAtom, uint32_t window,
                          uint32_t timestamp) {
    xcb_set_selection_owner(x->conn, window, selectionAtom, timestamp);
    xcb_flush(x->conn);
}

void xwmConvertSelection(XwmConn* x, uint32_t requestor, uint32_t selection,
                         uint32_t target, uint32_t property,
                         uint32_t timestamp) {
    xcb_convert_selection(x->conn, requestor, selection, target, property, timestamp);
    xcb_flush(x->conn);
}

void xwmSendSelectionNotify(XwmConn* x, uint32_t requestor,
                            uint32_t selection, uint32_t target,
                            uint32_t property, uint32_t timestamp) {
    xcb_selection_notify_event_t ev = {};
    ev.response_type = XCB_SELECTION_NOTIFY;
    ev.requestor = requestor;
    ev.selection = selection;
    ev.target = target;
    ev.property = property;  // 0 = refusal
    ev.time = timestamp;
    xcb_send_event(x->conn, /*propagate=*/0, requestor,
                   XCB_EVENT_MASK_NO_EVENT,
                   reinterpret_cast<const char*>(&ev));
    xcb_flush(x->conn);
}

void xwmXfixesSelectSelectionInput(XwmConn* x, uint32_t window,
                                   uint32_t selectionAtom, uint32_t mask) {
    if (!x->xfixesAvailable) return;
    xcb_xfixes_select_selection_input(x->conn, window, selectionAtom, mask);
    xcb_flush(x->conn);
}

uint32_t xwmInternAtom(XwmConn* x, const char* name) {
    if (!name || !*name) return 0;
    const size_t len = std::strlen(name);
    xcb_intern_atom_cookie_t c = xcb_intern_atom(
        x->conn, 0, static_cast<uint16_t>(len), name);
    xcb_intern_atom_reply_t* r = xcb_intern_atom_reply(x->conn, c, nullptr);
    if (!r) return 0;
    const uint32_t atom = r->atom;
    free(r);
    return atom;
}

uint32_t xwmGetAtomName(XwmConn* x, uint32_t atom) {
    if (atom == 0) return 0;
    xcb_get_atom_name_cookie_t c = xcb_get_atom_name(x->conn, atom);
    xcb_flush(x->conn);
    PendingAtomName p;
    p.cookieId = x->nextCookieId++;
    if (p.cookieId == 0) p.cookieId = x->nextCookieId++;  // skip sentinel
    p.atom = atom;
    p.sequence = c.sequence;
    x->pendingAtomName.push_back(p);
    return p.cookieId;
}

void xwmSelectWindowEvents(XwmConn* x, uint32_t window, uint32_t mask) {
    if (!x->conn || window == 0) return;
    const uint32_t values[1] = { mask };
    xcb_change_window_attributes(x->conn, window, XCB_CW_EVENT_MASK, values);
    xcb_flush(x->conn);
}

}  // namespace overdraw::xwayland
