// XWM policy (TS side). Consumes the decoded X events the native XWM
// (native/xwayland/xwm.cpp) delivers, resolves WL_SURFACE_SERIAL to the
// wl_surface Xwayland created, brings managed windows into overdraw's WM, and
// drives the ICCCM/EWMH property reads that yield title / app_id / size
// constraints / parent / presentation. The close path (WM_DELETE_WINDOW /
// KillClient) lives here too; it is invoked via closeXwaylandSurface.
//
// No xcb here -- the native side owns the X11 wire; this is window-management
// policy.

import type { CompositorState, SurfaceRecord } from "../protocols/ctx.js";
import type { Addon } from "../types.js";
import { markWindowChanged } from "../protocols/window-changes.js";
import { rebuildStackWithPopups } from "../protocols/xdg_popup.js";
import { ensureXwaylandState, lookupBySerial } from "./surface.js";
import { KEYBOARD_EVENT } from "../events/window-bus.js";
import {
  applyFocusToX as applyFocusToXPolicy,
  isFocusInStale,
} from "./focus.js";
import {
  parseStringProperty,
  parseWmClass,
  parseWmProtocols,
  parseNetWmState,
  parseNetWmWindowType,
  parseTransientFor,
  parseWmNormalHints,
  parseWmHints,
  netWmStateToPresentation,
  classifyWindowType,
  type PropertyAtoms,
  type PropertyReply,
} from "./properties.js";
import { xwaylandScaleOf } from "./scale.js";

export interface XwmEventMsg {
  type:
    | "create"
    | "destroy"
    | "map-request"
    | "map"
    | "unmap"
    | "configure-request"
    | "configure-notify"
    | "surface-serial"
    | "property-notify"
    | "property-reply"
    | "focus-in"
    | "xfixes-selection-notify"
    | "selection-request"
    | "selection-notify"
    | "atom-name-reply";
  window: number;
  x: number;
  y: number;
  width: number;
  height: number;
  overrideRedirect: boolean;
  serialLo: number;
  serialHi: number;
  atom?: number;
  cookieId?: number;
  replyType?: number;
  format?: number;
  data?: Uint8Array;
  // focus-in only: the X event's sequence (16-bit, widened to 32 on the
  // native side). TS compares against lastFocusSeq to drop FocusIns
  // generated by WM-initiated SetInputFocus calls.
  eventSequence?: number;
  // property-notify only: 0 = NewValue, 1 = Delete. The selection bridge
  // keys both INCR pumps off this distinction.
  propertyState?: number;
  // Selection-bridge fields.
  selection?: number;
  target?: number;
  property?: number;
  requestor?: number;
  selectionOwner?: number;
  timestamp?: number;
  // atom-name-reply only.
  name?: string;
}

export interface XWindow {
  window: number;             // X11 window id
  x: number;
  y: number;
  width: number;
  height: number;
  overrideRedirect: boolean;
  mapped: boolean;
  surfaceId: number | null;   // resolved via WL_SURFACE_SERIAL
  addedToWm: boolean;
  // Parsed ICCCM / EWMH properties. null until the corresponding property
  // reply has landed (or the property is absent).
  title: string | null;
  appId: string | null;
  wmProtocols: Set<number>;   // atoms (incl. WM_DELETE_WINDOW when supported)
  transientFor: number | null; // X window id of parent toplevel
  minSize: { width: number; height: number } | null;
  maxSize: { width: number; height: number } | null;
  windowKind: ReturnType<typeof classifyWindowType>;
  presentationHint: "fullscreen" | "maximized" | null;
  // WM_HINTS.input: null when the InputHint bit isn't set (ICCCM default
  // means treat as true). Drives the SetInputFocus vs WM_TAKE_FOCUS
  // decision per the ICCCM truth table.
  inputHint: boolean | null;
  // _NET_WM_PID: the X client's process id, used for the same-PID
  // exception in cross-app focus stealing (a single multi-window app
  // re-routing focus among its own windows is allowed; cross-PID
  // attempts are denied by refocusing the previous surface).
  pid: number | null;
}

// A narrow view stashed on CompositorState so unrelated modules (titleAppId,
// close-surface) can look up X-backed windows or initiate their close path
// without taking a dep on the full Xwm.
export interface XwmStateView {
  findBySurfaceId(surfaceId: number): XWindow | null;
  // Initiate close. Returns true iff a matching X window was found; the
  // close-surface helper uses that to skip the xdg branch.
  closeBySurfaceId(surfaceId: number): boolean;
}

export interface Xwm {
  stop(): void;
  windows(): ReadonlyMap<number, XWindow>;  // inspection (tests)
  // Initiate a close on an x-backed surface, by surfaceId. Sends a
  // WM_DELETE_WINDOW client-message when the client supports it, else
  // KillClient. Returns true iff a matching X window was found.
  closeBySurfaceId(surfaceId: number): boolean;
  // The selection bridge registers itself here so it can receive
  // selection-bridge events and claim property-notify deliveries on its own
  // per-transfer windows. `owner` returns true when the window id belongs to
  // a bridge-owned transfer; `hook` receives the four bridge event types
  // plus property-notify on bridge-owned windows.
  setSelectionHook(
    hook: ((ev: XwmEventMsg) => void) | null,
    owner: ((window: number) => boolean) | null,
  ): void;
  // The interned atom map (read-only). The selection bridge needs the
  // selection atoms (CLIPBOARD / PRIMARY / TARGETS / ...) to drive xcb.
  atoms(): Readonly<Record<string, number>>;
  // The X focus state visible to the WM, used by the bridge for focus
  // gating (X selection ownership claims only take effect when an X
  // client has X-side focus).
  xFocusedWindow(): number | null;
}

// All properties we batch-read on associate. PropertyNotify on any of these
// also re-reads only the one that changed.
function pickWatchedAtoms(atoms: Record<string, number>): Array<{ name: string; atom: number }> {
  const names = [
    "_NET_WM_NAME", "WM_NAME",
    "WM_CLASS",
    "WM_PROTOCOLS",
    "WM_NORMAL_HINTS",
    "WM_HINTS",
    "WM_TRANSIENT_FOR",
    "_NET_WM_STATE",
    "_NET_WM_WINDOW_TYPE",
    "_NET_WM_PID",
  ];
  return names.map((n) => ({ name: n, atom: atoms[n] ?? 0 })).filter((e) => e.atom !== 0);
}

function newXWindow(window: number, x: number, y: number, w: number, h: number,
                    overrideRedirect: boolean): XWindow {
  return {
    window, x, y, width: w, height: h, overrideRedirect,
    mapped: false, surfaceId: null, addedToWm: false,
    title: null, appId: null,
    wmProtocols: new Set<number>(),
    transientFor: null,
    minSize: null, maxSize: null,
    windowKind: null,
    presentationHint: null,
    inputHint: null,
    pid: null,
  };
}

// Helpers for the parsers that need the atom-name table. We type-assert here
// because the native side hands us an unstructured Record<string, number>;
// missing atoms (interned to 0) yield property-not-supported behavior in the
// parsers anyway.
function asPropertyAtoms(raw: Record<string, number>): PropertyAtoms {
  const a = (n: string): number => raw[n] ?? 0;
  return {
    WM_PROTOCOLS: a("WM_PROTOCOLS"),
    WM_DELETE_WINDOW: a("WM_DELETE_WINDOW"),
    WM_TAKE_FOCUS: a("WM_TAKE_FOCUS"),
    UTF8_STRING: a("UTF8_STRING"),
    _NET_WM_STATE_FULLSCREEN: a("_NET_WM_STATE_FULLSCREEN"),
    _NET_WM_STATE_MAXIMIZED_VERT: a("_NET_WM_STATE_MAXIMIZED_VERT"),
    _NET_WM_STATE_MAXIMIZED_HORZ: a("_NET_WM_STATE_MAXIMIZED_HORZ"),
    _NET_WM_STATE_MODAL: a("_NET_WM_STATE_MODAL"),
    _NET_WM_WINDOW_TYPE_NORMAL: a("_NET_WM_WINDOW_TYPE_NORMAL"),
    _NET_WM_WINDOW_TYPE_DIALOG: a("_NET_WM_WINDOW_TYPE_DIALOG"),
    _NET_WM_WINDOW_TYPE_UTILITY: a("_NET_WM_WINDOW_TYPE_UTILITY"),
    _NET_WM_WINDOW_TYPE_MENU: a("_NET_WM_WINDOW_TYPE_MENU"),
    _NET_WM_WINDOW_TYPE_DROPDOWN_MENU: a("_NET_WM_WINDOW_TYPE_DROPDOWN_MENU"),
    _NET_WM_WINDOW_TYPE_POPUP_MENU: a("_NET_WM_WINDOW_TYPE_POPUP_MENU"),
    _NET_WM_WINDOW_TYPE_TOOLTIP: a("_NET_WM_WINDOW_TYPE_TOOLTIP"),
    _NET_WM_WINDOW_TYPE_COMBO: a("_NET_WM_WINDOW_TYPE_COMBO"),
  };
}

export function startXwm(state: CompositorState, addon: Addon, wmFd: number): Xwm {
  const windows = new Map<number, XWindow>();
  // X windows that announced their serial before the wayland side registered
  // it; completed when onSerialRegistered fires for that serial.
  const pendingBySerial = new Map<bigint, XWindow>();
  // cookieId -> { window, atomName } for in-flight property reads.
  const pendingReads = new Map<number, { window: number; name: string }>();
  // surfaceId -> X window, populated on association. Cheap reverse lookup for
  // titleAppId / closeBySurfaceId.
  const bySurface = new Map<number, XWindow>();

  // Atoms are not available until xwmStart returns; provisional empty map
  // satisfies the type until then. (No property work happens before the
  // associate path, which runs after xwmStart resolves.)
  let atomsByName: Record<string, number> = {};
  let pa: PropertyAtoms = asPropertyAtoms({});

  ensureXwaylandState(state).onSerialRegistered = (serial, surfaceId) => {
    const w = pendingBySerial.get(serial);
    if (!w) return;
    pendingBySerial.delete(serial);
    w.surfaceId = surfaceId;
    onAssociated(w);
  };

  // A non-override-redirect window that is both mapped and associated with a
  // wl_surface enters the WM. Override-redirect windows take the placeOverlay
  // path instead -- they're transient overlays (menus / tooltips), not WM
  // windows.
  function maybeManage(w: XWindow): void {
    if (w.addedToWm || w.overrideRedirect || !w.mapped || w.surfaceId === null) return;
    const surfRec = state.surfacesById?.get(w.surfaceId);
    if (!surfRec || !state.wm) return;
    // Pick a spawn output: under the pointer if known, else the primary.
    // (X11 has no per-window output hint; the same fallback xdg_surface uses.)
    if (surfRec.spawnOutputId === undefined) {
      surfRec.spawnOutputId = state.wm.primaryOutputId?.();
    }
    state.wm.addWindow(w.surfaceId, surfRec);
    w.addedToWm = true;
    // Plumb the parsed properties (title/appId/constraints/parent/presentation)
    // into the WM now that the window is managed. Order: first markInitial so
    // window.map carries title/appId; then proposals for structural fields.
    publishInitial(w, surfRec);
  }

  function unmanage(w: XWindow): void {
    if (w.addedToWm && w.surfaceId !== null) state.wm?.unmapWindow(w.surfaceId);
    w.addedToWm = false;
  }

  // Override-redirect placement: record the X-supplied rect in
  // state.overrideRedirects so the content-layer stack rebuild
  // (xdg_popup.ts:appendOverrideRedirects) emits a setSurfaceLayout for
  // each OR overlay alongside the popup chain. The XWindow holds X-root
  // coords (device pixels at the X side's oversized view); divide by the
  // global X scale to land in compositor logical coords.
  function placeOverlay(w: XWindow): void {
    if (!w.overrideRedirect || !w.mapped || w.surfaceId === null) return;
    const ors = (state.overrideRedirects ??= new Map());
    const n = xwaylandScaleOf(state);
    ors.set(w.surfaceId, {
      x: Math.round(w.x / n),
      y: Math.round(w.y / n),
      width: Math.round(w.width / n),
      height: Math.round(w.height / n),
    });
    rebuildStackWithPopups(state);
  }

  function removeOverlay(w: XWindow): void {
    if (w.surfaceId === null) return;
    const ors = state.overrideRedirects;
    if (!ors || !ors.has(w.surfaceId)) return;
    ors.delete(w.surfaceId);
    rebuildStackWithPopups(state);
  }

  // When a window first associates with a wl_surface: batch-read every
  // ICCCM/EWMH property we care about. Each reply lands as a "property-reply"
  // event; the cookieId routes it back to the right window.
  function onAssociated(w: XWindow): void {
    if (w.surfaceId !== null) bySurface.set(w.surfaceId, w);
    const watched = pickWatchedAtoms(atomsByName);
    for (const e of watched) {
      const cookie = addon.xwmGetProperty(w.window, e.atom);
      pendingReads.set(cookie, { window: w.window, name: e.name });
    }
    // The window may already be mapped; if so, try to manage or place it
    // now (else wait for the map event). We do this AFTER firing the batch
    // reads so markInitialCommitComplete sees the still-null title/appId
    // only if no reply has come back yet -- and the subsequent
    // property-replies will markWindowChanged to publish the real values.
    if (w.overrideRedirect) placeOverlay(w);
    else maybeManage(w);
  }

  // Translate the parsed property state into wm.markInitialCommitComplete /
  // wm.propose calls. This mirrors the xdg_toplevel boot path (in
  // wl_surface.commit). Idempotent on re-call.
  function publishInitial(w: XWindow, _surfRec: SurfaceRecord): void {
    if (w.surfaceId === null || !state.wm) return;
    state.wm.markInitialCommitComplete?.(w.surfaceId, { appId: w.appId, title: w.title });
    sendStructuralProposals(w);
  }

  // Map parsed properties onto a wm.propose for structural fields. Called on
  // initial associate AND on PropertyNotify re-reads.
  function sendStructuralProposals(w: XWindow): void {
    if (w.surfaceId === null || !w.addedToWm || !state.wm) return;
    const proposal: Parameters<NonNullable<typeof state.wm>["propose"]>[1] = {};
    // Constraints: min/max from WM_NORMAL_HINTS.
    if (w.minSize !== null || w.maxSize !== null) {
      proposal.constraints = { minSize: w.minSize, maxSize: w.maxSize };
    }
    // Parent: WM_TRANSIENT_FOR -> the parent X window's surfaceId, if we know
    // it. (If the parent X window hasn't associated yet, we leave it null;
    // a later PropertyNotify will re-publish.)
    if (w.transientFor !== null) {
      const parent = windows.get(w.transientFor);
      if (parent && parent.surfaceId !== null) proposal.parent = parent.surfaceId;
    }
    // Presentation: derived from _NET_WM_STATE first, then a fallback
    // dialog-hint from _NET_WM_WINDOW_TYPE / WM_TRANSIENT_FOR. The dialog /
    // utility / menu kinds promote to floating via xdg's existing min==max
    // policy when constraints are set; we don't override presentation for
    // them.
    if (w.presentationHint !== null) {
      proposal.presentation = w.presentationHint;
    }
    if (Object.keys(proposal).length > 0) {
      void state.wm.propose(w.surfaceId, proposal, "client-request");
    }
  }

  // Apply a parsed property reply to the XWindow's state. Returns true iff a
  // user-observable field (title/appId) changed -- caller emits window.change.
  function applyProperty(w: XWindow, name: string, p: PropertyReply): boolean {
    let observableChanged = false;
    switch (name) {
      case "_NET_WM_NAME": {
        // _NET_WM_NAME (UTF-8) wins over WM_NAME (Latin-1) when present.
        const v = parseStringProperty(p, pa);
        if (v !== null && v !== w.title) { w.title = v; observableChanged = true; }
        break;
      }
      case "WM_NAME": {
        // Only honored when _NET_WM_NAME absent. We approximate by ignoring
        // WM_NAME if a non-null title was already set from _NET_WM_NAME this
        // session. PropertyNotify on WM_NAME after _NET_WM_NAME is rare; if it
        // happens, the next _NET_WM_NAME read re-wins.
        if (w.title === null) {
          const v = parseStringProperty(p, pa);
          if (v !== null && v !== w.title) { w.title = v; observableChanged = true; }
        }
        break;
      }
      case "WM_CLASS": {
        const v = parseWmClass(p);
        const next = v?.appId ?? null;
        if (next !== w.appId) { w.appId = next; observableChanged = true; }
        break;
      }
      case "WM_PROTOCOLS":
        w.wmProtocols = parseWmProtocols(p);
        break;
      case "WM_NORMAL_HINTS": {
        const v = parseWmNormalHints(p);
        w.minSize = v?.minSize ?? null;
        w.maxSize = v?.maxSize ?? null;
        sendStructuralProposals(w);
        break;
      }
      case "WM_HINTS": {
        const v = parseWmHints(p);
        w.inputHint = v?.input ?? null;
        break;
      }
      case "WM_TRANSIENT_FOR":
        w.transientFor = parseTransientFor(p);
        sendStructuralProposals(w);
        break;
      case "_NET_WM_STATE": {
        const states = parseNetWmState(p);
        w.presentationHint = netWmStateToPresentation(states, pa);
        sendStructuralProposals(w);
        break;
      }
      case "_NET_WM_WINDOW_TYPE": {
        const types = parseNetWmWindowType(p);
        w.windowKind = classifyWindowType(types, pa);
        break;
      }
      case "_NET_WM_PID": {
        // _NET_WM_PID is a single CARDINAL (u32). Drives the same-PID
        // exception for cross-app focus stealing in the FocusIn handler.
        if (p.format === 32 && p.data.byteLength >= 4) {
          const view = new DataView(
            p.data.buffer, p.data.byteOffset, p.data.byteLength);
          const pid = view.getUint32(0, true);
          w.pid = pid !== 0 ? pid : null;
        }
        break;
      }
    }
    return observableChanged;
  }

  function onEvent(ev: XwmEventMsg): void {
    switch (ev.type) {
      case "create":
        // (The bookkeeper window is filtered out on the native side; it
        // never reaches this dispatch.)
        windows.set(ev.window,
          newXWindow(ev.window, ev.x, ev.y, ev.width, ev.height, ev.overrideRedirect));
        break;
      case "map-request":
        // Allow the window to map; the compositor shows it once content arrives.
        addon.xwmMapWindow(ev.window);
        break;
      case "map": {
        const w = windows.get(ev.window);
        if (!w) break;
        // Native MapNotify carries the current X-side rect (it may differ
        // from CreateNotify's initial rect if the client called
        // ConfigureWindow in between, which OR windows often do to position
        // a menu). Sync the XWindow record first.
        if (ev.width > 0 && ev.height > 0) {
          w.x = ev.x; w.y = ev.y;
          w.width = ev.width; w.height = ev.height;
        }
        w.mapped = true;
        if (w.overrideRedirect) placeOverlay(w);
        else maybeManage(w);
        break;
      }
      case "unmap": {
        const w = windows.get(ev.window);
        if (w) {
          w.mapped = false;
          if (w.overrideRedirect) removeOverlay(w);
          else unmanage(w);
        }
        break;
      }
      case "destroy": {
        const w = windows.get(ev.window);
        if (w) {
          if (w.overrideRedirect) removeOverlay(w);
          else unmanage(w);
          if (w.surfaceId !== null) bySurface.delete(w.surfaceId);
        }
        windows.delete(ev.window);
        break;
      }
      case "configure-request": {
        // Managed windows: the compositor is authoritative -- reply with
        // the WM's current rect (and a synthetic ConfigureNotify per ICCCM
        // §4.2.3) instead of honoring the client's request. The WM rect
        // is in compositor logical coords; multiply by the global X scale
        // to land in X-device coords for the wire.
        // Override-redirect: the X client positions menus/tooltips itself;
        // honor the request (X coords passed through), update our tracked
        // rect (also X coords), and re-place the overlay so the compositor
        // draws it at the new coords.
        const n = xwaylandScaleOf(state);
        const w = windows.get(ev.window);
        if (w && w.addedToWm && w.surfaceId !== null) {
          const r = state.wm?.rectOf(w.surfaceId);
          if (r) {
            const xx = r.x * n, xy = r.y * n;
            const xw = r.width * n, xh = r.height * n;
            addon.xwmConfigureWindow(ev.window, xx, xy, xw, xh);
            addon.xwmSendConfigureNotify(ev.window, xx, xy, xw, xh);
            break;
          }
        }
        addon.xwmConfigureWindow(ev.window, ev.x, ev.y, ev.width, ev.height);
        addon.xwmSendConfigureNotify(ev.window, ev.x, ev.y, ev.width, ev.height);
        if (w) {
          w.x = ev.x; w.y = ev.y;
          w.width = ev.width; w.height = ev.height;
          if (w.overrideRedirect && w.mapped) placeOverlay(w);
        }
        break;
      }
      case "configure-notify": {
        // The X-side geometry actually changed (either our own
        // xwmConfigureWindow reflected back, or an override-redirect
        // client moved itself). Sync the XWindow record and -- for mapped
        // OR overlays -- re-place via the overrideRedirects store.
        const w = windows.get(ev.window);
        if (!w) break;
        w.x = ev.x; w.y = ev.y;
        w.width = ev.width; w.height = ev.height;
        if (w.overrideRedirect && w.mapped) placeOverlay(w);
        break;
      }
      case "surface-serial": {
        const serial = (BigInt(ev.serialHi >>> 0) << 32n) | BigInt(ev.serialLo >>> 0);
        const w = windows.get(ev.window);
        if (!w) break;
        const surfaceId = lookupBySerial(state, serial);
        if (surfaceId !== null) { w.surfaceId = surfaceId; onAssociated(w); }
        else pendingBySerial.set(serial, w);  // wayland side not registered yet
        break;
      }
      case "property-notify": {
        // A property change. The selection bridge claims notifications on its
        // own per-transfer windows (INCR pump); we ignore those here.
        if (selectionPropertyOwner?.(ev.window)) {
          selectionHook?.(ev);
          break;
        }
        const w = windows.get(ev.window);
        if (!w || ev.atom === undefined) break;
        const name = nameOfAtom(atomsByName, ev.atom);
        if (name === null) break;
        const cookie = addon.xwmGetProperty(ev.window, ev.atom);
        pendingReads.set(cookie, { window: ev.window, name });
        break;
      }
      case "property-reply": {
        if (ev.cookieId === undefined) break;
        const pend = pendingReads.get(ev.cookieId);
        if (!pend) {
          // The selection bridge issues its own xwmGetProperty calls; let
          // it claim replies whose cookieIds it minted.
          selectionHook?.(ev);
          break;
        }
        pendingReads.delete(ev.cookieId);
        const w = windows.get(pend.window);
        if (!w) break;  // window destroyed before reply arrived
        const reply: PropertyReply = {
          window: pend.window,
          atom: ev.atom ?? 0,
          cookieId: ev.cookieId,
          replyType: ev.replyType ?? 0,
          format: ev.format ?? 0,
          data: ev.data ?? new Uint8Array(0),
        };
        const observableChanged = applyProperty(w, pend.name, reply);
        if (observableChanged && w.addedToWm && w.surfaceId !== null) {
          // window.change ("title" / "appId") goes through the standard flush
          // (window-changes.ts), which calls back into titleAppId -- which
          // reads from XWindow now.
          markWindowChanged(state, w.surfaceId,
            pend.name === "WM_CLASS" ? "appId" : "title");
        }
        break;
      }
      case "focus-in":
        onFocusIn(ev);
        break;
      case "xfixes-selection-notify":
      case "selection-request":
      case "selection-notify":
      case "atom-name-reply":
        selectionHook?.(ev);
        break;
    }
  }

  // The selection bridge registers a hook here to receive selection-bridge
  // events (xfixes-selection-notify, selection-request, selection-notify,
  // atom-name-reply) and to claim property-notify deliveries on its own
  // per-transfer X windows. The hook returns true from onPropertyNotify
  // when it consumed the event (preventing the WM's property-watch path
  // from also touching it).
  let selectionHook:
    | ((ev: XwmEventMsg) => void)
    | null = null;
  let selectionPropertyOwner:
    | ((window: number) => boolean)
    | null = null;

  // Reverse-lookup atom -> name. The watched-atom list is small (~9 entries)
  // so a linear scan is fine; building an inverse map at startup would also work.
  function nameOfAtom(table: Record<string, number>, atom: number): string | null {
    for (const [name, value] of Object.entries(table)) {
      if (value === atom) return name;
    }
    return null;
  }

  const startResult = addon.xwmStart(wmFd, onEvent);
  atomsByName = startResult.atoms;
  pa = asPropertyAtoms(atomsByName);
  const root = startResult.root;
  const bookkeeper = startResult.bookkeeper;

  // Sequence of the most recent WM-initiated SetInputFocus, mirrored from
  // xwmSetInputFocus return values. The TS side compares incoming FocusIn
  // event sequences to filter stale events (e.g. our own SetInputFocus
  // reflecting back, or a client's XSetInputFocus that lost the race).
  let lastFocusSeq = 0;

  // The X window we most recently SetInputFocus'd (or null when X focus is
  // parked on the bookkeeper). Drives the previous-window state when the
  // next focus transition arrives.
  let xFocusedWindow: XWindow | null = null;

  // Helper: convert _NET_WM_STATE_FOCUSED to/from a window's _NET_WM_STATE
  // atom list. EWMH says the WM owns _NET_WM_STATE_FOCUSED; clients OR it
  // with whatever client-set state atoms they keep (fullscreen, etc.). We
  // write the full list since we already track it on XWindow.presentationHint
  // -- but that's lossy (we collapse fullscreen/maximized down). Safer:
  // re-read the current property and add/remove the FOCUSED atom on the
  // existing list. Cheaper alternative: just always write either {FOCUSED}
  // or {} -- clients that care about other _NET_WM_STATE bits set them
  // themselves and overwrite us; clients that only react to FOCUSED don't
  // care. Going with the cheap option for v1; flagged.
  function setStateFocused(window: number, focused: boolean): void {
    if (focused) {
      const buf = new Uint32Array([pa.WM_TAKE_FOCUS]);  // placeholder; replaced below
      // Reuse the buffer view to send a single _NET_WM_STATE_FOCUSED atom.
      buf[0] = atomsByName._NET_WM_STATE_FOCUSED ?? 0;
      if (buf[0] === 0) return;
      addon.xwmChangeProperty(
        window, atomsByName._NET_WM_STATE ?? 0,
        4 /*ATOM*/, 32, buf, 1);
    } else {
      // Clear the property entirely. See the comment above: this clobbers
      // any client-set _NET_WM_STATE bits; in practice the client just
      // re-asserts them via change_property if it cares.
      addon.xwmDeleteProperty(window, atomsByName._NET_WM_STATE ?? 0);
    }
  }

  function setNetActiveWindow(window: number): void {
    const buf = new Uint32Array([window]);
    addon.xwmChangeProperty(
      root, atomsByName._NET_ACTIVE_WINDOW ?? 0,
      33 /*WINDOW*/, 32, buf, 1);
  }

  // Dispatch a planned FocusAction. Records lastFocusSeq from SetInputFocus
  // calls so the FocusIn handler can filter stale events.
  function dispatchFocusAction(a: import("./focus.js").FocusAction): void {
    switch (a.kind) {
      case "set-input-focus":
        lastFocusSeq = addon.xwmSetInputFocus(a.window, 0 /*XCB_CURRENT_TIME*/);
        break;
      case "send-take-focus":
        addon.xwmSendWmProtocol(
          a.window, pa.WM_TAKE_FOCUS, 0 /*XCB_CURRENT_TIME*/);
        break;
      case "set-net-active-window":
        setNetActiveWindow(a.window);
        break;
      case "set-state-focused":
        setStateFocused(a.window, true);
        break;
      case "clear-state-focused":
        setStateFocused(a.window, false);
        break;
    }
  }

  function focusTargetOf(w: XWindow | null): import("./focus.js").XFocusTarget | null {
    if (!w) return null;
    return {
      window: w.window,
      inputHint: w.inputHint,
      hasTakeFocus: w.wmProtocols.has(pa.WM_TAKE_FOCUS),
      overrideRedirect: w.overrideRedirect,
    };
  }

  // The KEYBOARD_EVENT.focus subscriber. The compositor's seat fires this
  // on every kbFocus transition (see wl_seat.ts:setKbFocus). We translate
  // (prevSurfaceId, surfaceId) into an X-side focus plan and dispatch.
  function onSeatFocusChanged(ev: import("../events/window-bus.js").KeyboardFocusEvent): void {
    const prev = ev.prevSurfaceId !== null ? bySurface.get(ev.prevSurfaceId) ?? null : null;
    const next = ev.surfaceId !== null ? bySurface.get(ev.surfaceId) ?? null : null;
    const actions = applyFocusToXPolicy(
      focusTargetOf(prev), focusTargetOf(next), bookkeeper);
    for (const a of actions) dispatchFocusAction(a);
    // Track the X window we most recently focused (or null when focus left X).
    xFocusedWindow = next && !next.overrideRedirect ? next : null;
  }

  const focusUnsub = state.bus?.on(KEYBOARD_EVENT.focus, onSeatFocusChanged);

  function closeBySurfaceId(surfaceId: number): boolean {
    const w = bySurface.get(surfaceId);
    if (!w) return false;
    if (w.wmProtocols.has(pa.WM_DELETE_WINDOW)) {
      addon.xwmSendWmProtocol(w.window, pa.WM_DELETE_WINDOW);
    } else {
      addon.xwmKillClient(w.window);
    }
    return true;
  }

  // X -> compositor focus signal. An X client called XSetInputFocus on its
  // own (or our own SetInputFocus reflected back). Use lastFocusSeq to
  // filter stale events; on a real cross-window focus shift, apply the
  // same-PID exception (allow same-app re-focusing) or refocus the
  // previous window (deny cross-app focus stealing).
  function onFocusIn(ev: XwmEventMsg): void {
    if (ev.eventSequence === undefined) return;
    if (isFocusInStale(ev.eventSequence, lastFocusSeq)) return;
    const target = windows.get(ev.window);
    if (!target || target.overrideRedirect) return;  // OR self-focus is fine; we don't mirror
    // Skip the bookkeeper window itself; we focused it deliberately.
    if (ev.window === bookkeeper) return;

    const current = xFocusedWindow;
    if (target === current) return;  // already the focused window; nothing to do

    // Same-PID exception: a multi-window app re-focusing among its own
    // windows is allowed. Update _NET_ACTIVE_WINDOW + _NET_WM_STATE_FOCUSED
    // to reflect the X-side change; do NOT propagate to the seat (the
    // seat is the source of truth for Wayland input routing).
    if (current && target.pid !== null && current.pid !== null
        && target.pid === current.pid) {
      // Clear old, set new.
      setStateFocused(current.window, false);
      setStateFocused(target.window, true);
      setNetActiveWindow(target.window);
      xFocusedWindow = target;
      return;
    }

    // Cross-PID / unknown-PID focus shift: deny focus stealing by
    // refocusing the previous window. The previous SetInputFocus also
    // bumps lastFocusSeq so the subsequent FocusIn from this refocus is
    // filtered.
    if (current) {
      lastFocusSeq = addon.xwmSetInputFocus(current.window, 0);
    } else {
      // No previous X focus: park on the bookkeeper.
      lastFocusSeq = addon.xwmSetInputFocus(bookkeeper, 0);
    }
  }

  // Stash a view on CompositorState so titleAppId / closeSurface can reach
  // x-backed windows without taking a dep on the full Xwm.
  state.xwm = {
    findBySurfaceId(surfaceId) { return bySurface.get(surfaceId) ?? null; },
    closeBySurfaceId,
  };

  return {
    stop() {
      focusUnsub?.();
      addon.xwmStop();
      state.xwm = undefined;
    },
    windows() { return windows; },
    closeBySurfaceId,
    setSelectionHook(hook, owner) {
      selectionHook = hook;
      selectionPropertyOwner = owner;
    },
    atoms() { return atomsByName; },
    xFocusedWindow() {
      return xFocusedWindow ? xFocusedWindow.window : null;
    },
  };
}
